!!python/object:langchain_community.agent_toolkits.openapi.spec.ReducedOpenAPISpec
description: The Open Movie Database. The OMDb API is a free web service to obtain
  movie information, all content and images on the site are contributed and maintained
  by our users.
endpoints:
- !!python/tuple
  - GET /
  - Find a movie, series or episode from the OMDb by title, IMDb-id or by free-text
    search
  - description: Find a movie, series or episode from the OMDb by title, IMDb-id or
      by free-text search
    parameters:
    - description: The data type to return.
      in: query
      name: r
      required: true
      schema:
        default: json
        enum:
        - json
        - xml
        type: string
    responses:
      content:
        application/json:
          schema:
            properties:
              Actors:
                type: string
              Awards:
                type: string
              BoxOffice:
                type: string
              Country:
                type: string
              DVD:
                type: string
              Director:
                type: string
              Genre:
                type: string
              Language:
                type: string
              Metascore:
                type: string
              Plot:
                type: string
              Poster:
                type: string
              Production:
                type: string
              Rated:
                type: string
              Released:
                type: string
              Response:
                type: string
              Runtime:
                type: string
              Search:
                items:
                  properties:
                    Poster:
                      type: string
                    Title:
                      type: string
                    Type:
                      type: string
                    Year:
                      type: string
                    imdbID:
                      type: string
                  required:
                  - Poster
                  - Title
                  - Type
                  - Year
                  - imdbID
                  type: object
                type: array
              Title:
                type: string
              Type:
                type: string
              Website:
                type: string
              Writer:
                type: string
              Year:
                type: string
              imdbID:
                type: string
              imdbRating:
                type: string
              imdbVotes:
                type: string
              tomatoConsensus:
                type: string
              tomatoFresh:
                type: string
              tomatoImage:
                type: string
              tomatoMeter:
                type: string
              tomatoRating:
                type: string
              tomatoReviews:
                type: string
              tomatoRotten:
                type: string
              tomatoURL:
                type: string
              tomatoUserMeter:
                type: string
              tomatoUserRating:
                type: string
              tomatoUserReviews:
                type: string
              totalResults:
                type: string
              totalSeasons:
                type: string
            required:
            - Response
            type: object
        application/xml:
          schema:
            properties:
              Actors:
                type: string
              Awards:
                type: string
              BoxOffice:
                type: string
              Country:
                type: string
              DVD:
                type: string
              Director:
                type: string
              Genre:
                type: string
              Language:
                type: string
              Metascore:
                type: string
              Plot:
                type: string
              Poster:
                type: string
              Production:
                type: string
              Rated:
                type: string
              Released:
                type: string
              Response:
                type: string
              Runtime:
                type: string
              Search:
                items:
                  properties:
                    Poster:
                      type: string
                    Title:
                      type: string
                    Type:
                      type: string
                    Year:
                      type: string
                    imdbID:
                      type: string
                  required:
                  - Poster
                  - Title
                  - Type
                  - Year
                  - imdbID
                  type: object
                type: array
              Title:
                type: string
              Type:
                type: string
              Website:
                type: string
              Writer:
                type: string
              Year:
                type: string
              imdbID:
                type: string
              imdbRating:
                type: string
              imdbVotes:
                type: string
              tomatoConsensus:
                type: string
              tomatoFresh:
                type: string
              tomatoImage:
                type: string
              tomatoMeter:
                type: string
              tomatoRating:
                type: string
              tomatoReviews:
                type: string
              tomatoRotten:
                type: string
              tomatoURL:
                type: string
              tomatoUserMeter:
                type: string
              tomatoUserRating:
                type: string
              tomatoUserReviews:
                type: string
              totalResults:
                type: string
              totalSeasons:
                type: string
            required:
            - Response
            type: object
      description: Default response
servers:
- url: http://www.omdbapi.com/
- url: https://www.omdbapi.com/
